CREATE TABLE VILLE (
    nom_ville VARCHAR(200) NOT NULL,
    longi REAL NOT NULL,
    lati REAL NOT NULL,
    region VARCHAR(200) NOT NULL,
    pays VARCHAR(200) NOT NULL,
    PRIMARY KEY (nom_ville)
);
CREATE TABLE CHAMBRE (
    code_c INTEGER NOT NULL,
    surface REAL NOT NULL,
    PRIMARY KEY (code_c)
);
CREATE TABLE AGENCE_DE_VOYAGE (
    code_a INTEGER NOT NULL,
    site_web TEXT NOT NULL,
    telephone VARCHAR(200) NOT NULL,
    Adresse_code_postal INTEGER NOT NULL,
    Adresse_rue_a VARCHAR(200) NOT NULL,
    Adresse_num_a INTEGER NOT NULL,
    Adresse_pays_a VARCHAR(200) NOT NULL,
    VILLE_nom_ville VARCHAR(200) NOT NULL,
    PRIMARY KEY (code_a),
    FOREIGN KEY (VILLE_nom_ville) REFERENCES VILLE (nom_ville)
);
CREATE TABLE RESERVATION (
    CHAMBRE_code_c INTEGER NOT NULL,
    data_d DATE NOT NULL,
    data_f DATE NOT NULL,
    prix REAL NOT NULL,
    AGENCE_DE_VOYAGE_code_a INTEGER NOT NULL,
    PRIMARY KEY (CHAMBRE_code_c, data_d),
    FOREIGN KEY (CHAMBRE_code_c) REFERENCES CHAMBRE (code_c),
    FOREIGN KEY (AGENCE_DE_VOYAGE_code_a) REFERENCES AGENCE_DE_VOYAGE (code_a)
);
CREATE TABLE SUITE (
    CHAMBRE_code_c INTEGER NOT NULL,
    PRIMARY KEY (CHAMBRE_code_c),
    FOREIGN KEY (CHAMBRE_code_c) REFERENCES CHAMBRE (code_c)
);
CREATE TABLE HAS_ESPACE_DISPO (
    ESPACE_DISPO_espace_dispo VARCHAR(200) NOT NULL,
    SUITE_CHAMBRE_code_c INTEGER NOT NULL,
    PRIMARY KEY (ESPACE_DISPO_espace_dispo, SUITE_CHAMBRE_code_c),
    FOREIGN KEY (SUITE_CHAMBRE_code_c) REFERENCES SUITE (CHAMBRE_code_c)
);
CREATE TABLE HAS_EQUIPEMENT (
    CHAMBRE_code_c INTEGER NOT NULL,
    EQUIPEMENT_equipement VARCHAR(200) NOT NULL,
    PRIMARY KEY (CHAMBRE_code_c, EQUIPEMENT_equipement),
    FOREIGN KEY (CHAMBRE_code_c) REFERENCES CHAMBRE (code_c)
);